### PR TITLE
Make compatible with Python 2.7

### LINKED ISSUE #4: Does not compile in Python 2.7
The extension won't compile in Python 2.7:

```
    src/ccurlmodule.c:205:8: error: unknown type name 'PyModuleDef'
    static PyModuleDef ccurlmodule = {
           ^
    src/ccurlmodule.c:206:3: error: use of undeclared identifier 'PyModuleDef_HEAD_INIT'
      PyModuleDef_HEAD_INIT,
      ^
    src/ccurlmodule.c:220:5: error: void function 'PyInit_ccurl' should not return a value [-Wreturn-type]
        return NULL;
        ^      ~~~~
    src/ccurlmodule.c:222:7: warning: implicit declaration of function 'PyModule_Create' is invalid in C99 [-Wimplicit-function-declaration]
      m = PyModule_Create(&ccurlmodule);
          ^
    src/ccurlmodule.c:224:5: error: void function 'PyInit_ccurl' should not return a value [-Wreturn-type]
        return NULL;
        ^      ~~~~
    src/ccurlmodule.c:228:5: error: void function 'PyInit_ccurl' should not return a value [-Wreturn-type]
        return NULL;
        ^      ~~~~
    src/ccurlmodule.c:238:3: error: void function 'PyInit_ccurl' should not return a value [-Wreturn-type]
      return m;
      ^      ~
    1 warning and 6 errors generated.
    error: command '/usr/bin/clang' failed with exit status 1
```

This appears to be due to changes introduced in the Python C API during the transition to version 3:  
https://docs.python.org/3/howto/cporting.html

### PR DESCRIPTION
**Pull request by etiennekruger**
This commit adds some conditional C code to ensure that the module
works under Python 2.7 as well as Python 3. Trits are treated as PyInt
under Python 2.7 but PyLong under Python 3 because Python 3 handles
all Python integers as PyLong.

Fixes #4.

### CODE REVIEW

**Comment by etiennekruger** [comment]
For testing I made the change below in https://github.com/iotaledger/iota.lib.py and ran the full PyOTA test suite under Python 2.7.
```
diff --git a/src/iota/crypto/__init__.py b/src/iota/crypto/__init__.py
index 63ca830..4cfe576 100644
--- a/src/iota/crypto/__init__.py
+++ b/src/iota/crypto/__init__.py
@@ -5,8 +5,11 @@ from __future__ import absolute_import, division, print_function, \
 
 # Load curl library.
 # If a compiled c extension is available, we will prefer to load that
-# (once implemented).
-from .pycurl import *
+# and fall back to the pure Python implementation if not.
+try:
+    from ccurl import *
+except ImportError:
+    from .pycurl import *
 
 
 FRAGMENT_LENGTH = 2187

```
